### ISSUE TITLE
remove airglow from all lines at once 

### ISSUE THREAD

**Issue by davidjwilson** [AstroAguirre/subtractAirglow#2]
Currently "Remove Airglow" and "Save Recovered Spectrum" produces a spectrum where the airglow has only been removed from whichever line happens to be selected in the GUI, even if all lines have been fitted. It would be very useful to be able to save a spectrum where airglow has been removed from all four lines.

**Comment by AstroAguirre** [comment]
This has been resolved as an order of operations issue, where "Remove Airglow" was only being pressed for one emission line rather than for all four as intended. Once all four are fitted and 'removed', the "Save Recovered Spectrum" button will produce a spectrum with all four emission lines subtracted.
